# Generated by Django 5.2.7 on 2025-11-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Parisina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
    ]
